name: Deploy web-app via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy peers-for-peers web-app

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build website
        env:
          # Point peers-for-peers website client at shared (federated) p2panda node
          ENDPOINT: https://welle.liebechaos.org/graphql
        run: npm run build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: p4p.offline.place
